# Supabase PostgreSQL Integration
# Replace [YOUR-PASSWORD] and [YOUR-PROJECT-REF] with your Supabase Database credentials
spring.datasource.url=jdbc:postgresql://db.sfzazlloxecvmxxrligx.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Admin@Password26
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload Limit Configuration for Question Images
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB